#! /bin/sh
wmname LG3D &
vmware-user-suid-wrapper &

pgrep -x sxhkd > /dev/null || sxhkd &


if xrandr -q | grep 'HDMI-0 connected'; then
    xrandr --output eDP-1-0 --mode 1920x1080 --rate 144 --primary 
    xrandr --output HDMI-0 --mode 2560x1440 --rate 144 --right-of eDP-1-0
    bspc monitor eDP-1-0 -d I II III IV V
    bspc monitor HDMI-0 -d VI VII VIII IX X
elif xrandr -q | grep 'eDP-1-0 connected'; then
    xrandr --output eDP-1-0 --mode 1920x1080
    bspc monitor eDP-1-0 -d I II III IV V VI VII VIII IX X
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap          15
bspc config bottom_padding      5
bspc config left_padding        18
bspc config right_padding       18

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^10' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

 rule -a ".*" manage=on


# CUSTOM
bspc config focus_follows_pointer true

# DUNST
killall -q dunst
dunst &

# POLYBAR
killall -q polybar
~/.config/polybar/launch.sh


killall -q conky
/home/sebas/.config/conky/Betelgeuse/start.sh &


/home/sebas/scripts/background.sh

# PICOM
picom --vsync &
bspc config border_width 0

xsetroot -cursor_name left_ptr &
